### ISSUE TITLE
Stars aren't generated uniformly when moving almost vertically

### ISSUE THREAD

**Issue by Minoru** [tsoding/space#1]
When the "ship" is moving *almost* vertically, there are more stars generated at the screen edge on one side of the "ship" than the other. Here's a few screenshots:
![2016-11-01-173103_1366x768_scrot](https://cloud.githubusercontent.com/assets/118875/19893223/7c41e6ba-a059-11e6-9600-7ef8f95c7d12.png)
![2016-11-01-173114_1366x768_scrot](https://cloud.githubusercontent.com/assets/118875/19893228/8166e53c-a059-11e6-8df5-13373ea618c2.png)

**Comment by rexim** [comment]
Yes, I'm aware of that problem. Just too lazy to capture that as usual. Thanks for filing it!
